### ISSUE TITLE
I was trying to get the chat example to work

### ISSUE THREAD

**Issue by rschlack** [TuneHQ/cookbook#15]
The README.md file is empty for the chat app.  Doesn't seem to be any docs at all.  Is there any info on how to run this locally?

**Comment by cshubhamrao** [comment]
here is the accompanying guide, [chat app with threads API and Next JS](https://studio.tune.app/docs/cookbook/chat-app-with-threads-api-and-next-js). we missed to link it from the README, sorry

**Comment by abhishekmishragithub** [comment]
@rschlack were you able to do this? if you are still facing the issue then please join our discord here: https://discord.gg/cAngpgp4
